### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-binder#1]
closes https://github.com/mne-tools/mne-python/issues/2906
- [x] install conda and pip dependencies
- [x] install mne
- [x] download ipynb
- [x] dynamically populate ipynb to `/home/main/notebooks/` (https://github.com/binder-project/binder/issues/60)
- [ ] add links to binder notebooks to html build
- [ ] download all datasets
- [ ] make mayavi examples/tutorials output [screenshots](http://docs.enthought.com/mayavi/mayavi/auto/mlab_figure.html#screenshot) to make them compatible with jupyter
- [ ] check compatibility matplotlib and mayavi env in binder jupyter
- [ ] add test to binder build?
- [ ] use `ylm` instead of `Dockerfile`?
- [ ] add class walkthrough: e.g. https://github.com/mne-tools/mne-python-notebooks (will require rep cleanup)
- [ ] test all ipynb

**Comment by kingjr** [comment]
I'll PR my branch once [binder status](http://mybinder.org/repo/kingjr/mne-binder/status) is cleared (it is still downloading and installing everything).

**Comment by kingjr** [comment]
@Eric89GXL you can checkout http://mybinder.org/repo/mne-tools/mne-binder, it can take a while to load, but it seems to be working.

I did `mne.datasets.sample.data_path()` at the installation, but that doesn't seem to download all datasets. Eg. this downloads something.

```
from mne.datasets import spm_face
data_path = spm_face.data_path()
```

We probably need to have a word with binder people though. I'm not sure how much data we can/should put.

**Comment by agramfort** [comment]
really cool !

i am bluffed.

nice job @kingjr

**Comment by larsoner** [comment]
Awesome :)

Yes it won't download everything. Maybe for now we should only include examples that use `sample` to avoid taking up too much space. Or really, we should just pick just a few. I would suggest something like:
1. Intro so people can see how it's easy to use.
2. From raw->dSPM so people can see that.
3. One or two cool eye-candy ones.

Thinking about it more, I don't think we need to include everything -- just enough to get people enticed to try it on their own systems. WDYT?

**Comment by larsoner** [comment]
...actually, one example for each bullet point in our "what can MNE do" list would be a great start.

**Comment by kingjr** [comment]
@Eric89GXL Yes we can prioritize:
1. Binder is planning on making encapsulable cells, so the intro would really benefit from this.
2. IMO it would be great to have all tutorials in ipynb. When teaching (which I don't) putting people on binder would save time with regard to the installation part. All but 2 tutorials use the `sample` data set (`plot_sensor_time_frequency` uses `somato`, and  `brain_storm` mimics the brainstorm tutorial), so it should be fine with the current setup. Note that it's easy to setup binder on aws, so if you need to setup computation-intensive classes, it could also be something to think about.
3. with regard to http://mne-tools.github.io/dev/getting_started.html#what-can-you-do, the bullet points are not linked to examples/tutorials? I suspect that it will be redundant to the tutorials.

>  I am bluffed.

Had you not tried it already for my [last submission](https://github.com/kingjr/decoding_unconscious_maintenance) ;) ? e.g. http://mybinder.org/repo/kingjr/decoding_unconscious_maintenance/notebook/results_summary.ipynb

**Comment by larsoner** [comment]
We should probably make those bold things link to tutorials as we do them. @agramfort WDYT?

Once this works well, maybe we could add a link at the bottom of each tutorials page with a "Try it!" or something. Did you have any other ideas for how to integrate it with the docs?

**Comment by agramfort** [comment]
a click to the mybinder below each tutorial would be neat.

this should be done at the sphinx-gallery level.

**Comment by kingjr** [comment]
> Did you have any other ideas for how to integrate it with the docs?

Once binder makes is encapsulable, we could try to make them render in the webpage; but I suspect this will create several issues (delay, binder server issues etc). For now, +1 for just a link.

I would also advertise this feature directly in the frontpage, since we're trying to hook new/naive users.

**Comment by agramfort** [comment]
> I would also advertise this feature directly in the frontpage, since we're
> trying to hook new/naive users.

that's an easy first move +1

**Comment by larsoner** [comment]
@kingjr anything I can do to help move this forward?

**Comment by kingjr** [comment]
I had stopped because binder was starting to be unreliable (stuck at
connection time) . But I can try to give it a look next week. Itmt you can
give it a try if you fancy it.

**Comment by larsoner** [comment]
Closing this in favor of the MNE-Python discussion to keep it simple
